// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using rentVPSmicroservices.microserviceConfig.Contexts;

#nullable disable

namespace rentVPSmicroservices.microserviceConfigs.Migrations
{
    [DbContext(typeof(ConfigContext))]
    [Migration("20251025145905_DefaultMigration")]
    partial class DefaultMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("rentVPSmicroservices.microserviceConfigs.Models.Configuration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("CPU_ghz")
                        .HasColumnType("real");

                    b.Property<string>("CPU_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GPU_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GPU_vram")
                        .HasColumnType("integer");

                    b.Property<string>("OS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RAM")
                        .HasColumnType("integer");

                    b.Property<int>("disk_size")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Configurations");
                });
#pragma warning restore 612, 618
        }
    }
}
