// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using rentVPSmicroservices.microserviceOrder.Contexts;

#nullable disable

namespace rentVPSmicroservices.microserviceOrders.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20251025183441_BasicMigration")]
    partial class BasicMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("rentVPSmicroservices.microserviceOrders.Models.Order", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("configGuid")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<float>("rentPerMonth")
                        .HasColumnType("real");

                    b.Property<Guid>("userGuid")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
